spring:
  application:
    name: "configserver"
  profiles:
    #active: native #if we are using classpath location or filesystem location
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main #repo branch
          timeout: 5 #wait for maximum 5 seconds, throw exception otherwise
          clone-on-start: true #clone the github repo into local system during startup
          force-pull: true #config server always reads properties from the github repo

encrypt:
  key: "iZ111om/YnTZ9IOoHVnkhmRTwzoIQ21B8jCBKJnDDHQVY2o1i3dyVBmvPpPHRjXW"


server:
  port: 8071
