server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod" #by default, it will activate prod profile on config server
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/" #optional can be removed according to situation

management:
  endpoints:
    web:
      exposure:
        include: "*" #Enable and expose all management endpoint supported by the spring boot actuator, inside these endpoints we are also going to have refresh related endpoints


